version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Print Message
          command: echo "Executing the build job..."

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
